name: Truth in Running
favicon: null
layout_spectrum: 0.29511563503183424
typography_spectrum: 0.5160226868465543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.34732419485226274
  lightness: 0.7324172360822558
  saturation: 0.36294498899951577
  rhythmicContrast: 0.02954271691851318
purpose: []
